# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.12.0.schema.json

PackageIdentifier: GoversoftLLC.PrivaZer
PackageVersion: 4.0.120.3
PackageLocale: en-US
Publisher: Goversoft LLC
PackageName: PrivaZer
License: Proprietary
Copyright: Goversoft LLC 2010
ShortDescription: One of the best free PC cleaner
InstallerType: exe
InstallerSwitches:
  Silent: -silent
  SilentWithProgress: -silent
Installers:
- Architecture: x86
  InstallerUrl: https://dl.volan.top/winget-repo/manifests/g/GoversoftLLC/PrivaZer/4.0.120.3/PrivaZer_free.exe
  InstallerSha256: A07CC599777C89E956A2A392AAB8E6746D8E76E9944482EDA9F5008407DDE256
ManifestType: singleton
ManifestVersion: 1.12.0
